### ISSUE TITLE
hiding the events that are over in the past on home page

### ISSUE THREAD

**Issue by outstanding-hare** [misty-meadow/mgt656-spring-2015-project#26]

**Comment by outstanding-hare** [comment]
https://www.youtube.com/watch?v=1QkK52kdKWg&index=4&list=PLEsf0fWhK8Xmi20t1VARjefbwAI5abiDQ
this is kyle's video 

However by following the instructions and deleting 
'events'=events.all and replacing that with 'events'=[] we are not able to achieve the required result. Need to check with the TAs or Kyle

**Comment by Ettie19** [comment]
I fixed the code. -Ettie

**Comment by outstanding-hare** [comment]
What did you change?

**Comment by Ettie19** [comment]
I just did 'events' : [], and it worked
