### ISSUE TITLE
tests for validating the input types on create event page

### ISSUE THREAD

**Issue by outstanding-hare** [misty-meadow/mgt656-spring-2015-project#27]

**Comment by outstanding-hare** [comment]
Despite having tried the same code as Kyle on the video https://www.youtube.com/watch?v=_nxBcIFTn7E&index=9&list=PLEsf0fWhK8Xmi20t1VARjefbwAI5abiDQ
the tests failed. Issue unknown.

**Comment by Ettie19** [comment]
Redid some of the code. Some of the fields are capitalized (e.g. Day) while some are lowercase (e.g. minute). I'm not sure why the fields are written this way and don't have time to fix now, so we need to fix this.
